spring:
  application:
    name: bookstore
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  datasource:
    url: jdbc:sqlite:db.sqlite3
    driverClassName: org.sqlite.JDBC

hibernate:
  hbm2ddl:
    auto: create-drop

logging:
  level:
    org.hibernate.orm.connections.pooling: off
    com.zaxxer.hikari: off

user:
  users:
    user:
      username: user
      password: userpass
      roles:
        - USER
    admin:
      username: admin
      password: adminpass
      roles:
        - USER
        - ADMIN